# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - merchant-id

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://cryptomapp.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_6fa3b40e08894e1bb7c43cd8fd6721da }}
        password: ${{ secrets.AzureAppService_ContainerPassword_f321f16ec66b43028d5cc260687a2128 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: cryptomapp.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_6fa3b40e08894e1bb7c43cd8fd6721da }}/merchant-id:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'merchant-id'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_4bd720878abd4ae79c099de03acafc2f }}
        images: 'cryptomapp.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_6fa3b40e08894e1bb7c43cd8fd6721da }}/merchant-id:${{ github.sha }}'